[tool.poetry]
name = "poetry-editable"
version = "0.1.0"
description = ""
authors = [{ name = "Astral Software Inc.", email = "hey@astral.sh" }]

[tool.poetry.dependencies]
python = "^3.10"
anyio = "^4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
